// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJHkQ0-5gAcqAgASe9Jz4DdLhUz2-L0VE',
    appId: '1:293350427052:web:fb4b1bba30bae6ddce5209',
    messagingSenderId: '293350427052',
    projectId: 'proyectodelivery-1de17',
    authDomain: 'proyectodelivery-1de17.firebaseapp.com',
    storageBucket: 'proyectodelivery-1de17.appspot.com',
    measurementId: 'G-EQW59B2JYG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAinOVCsOm9fkGc7375W7S9t3nkoHfUXUk',
    appId: '1:293350427052:android:39cc0f75654251dfce5209',
    messagingSenderId: '293350427052',
    projectId: 'proyectodelivery-1de17',
    storageBucket: 'proyectodelivery-1de17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-KY1G9RImP5DrdOHOGOyGYszf56VIzwo',
    appId: '1:293350427052:ios:0d8c528c3e8c04fbce5209',
    messagingSenderId: '293350427052',
    projectId: 'proyectodelivery-1de17',
    storageBucket: 'proyectodelivery-1de17.appspot.com',
    iosClientId: '293350427052-1dk777ltjan26cup2044k5ef4b7i5f2b.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-KY1G9RImP5DrdOHOGOyGYszf56VIzwo',
    appId: '1:293350427052:ios:0d8c528c3e8c04fbce5209',
    messagingSenderId: '293350427052',
    projectId: 'proyectodelivery-1de17',
    storageBucket: 'proyectodelivery-1de17.appspot.com',
    iosClientId: '293350427052-1dk777ltjan26cup2044k5ef4b7i5f2b.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDelivery',
  );
}
